# Generated by Django 2.2.18 on 2021-10-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20210724_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='mockModalStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, null=True)),
                ('last_name', models.CharField(default='', max_length=255, null=True)),
                ('grad_year', models.IntegerField(blank=True, null=True)),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
